# Generated by Django 4.1.13 on 2024-10-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code (e.g., 'us' for United States')",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full country name (e.g., 'United States')",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "start",
                    models.CharField(
                        blank=True,
                        help_text="Start date (e.g., 'August 2023')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "end",
                    models.CharField(
                        blank=True,
                        help_text="End date (e.g., 'September 2023')",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="React",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("line_name", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("class_field", models.CharField(blank=True, max_length=50)),
                ("bigId", models.IntegerField(blank=True, null=True)),
                ("littleIds", models.JSONField(blank=True, default=list, null=True)),
                ("major", models.CharField(blank=True, max_length=100)),
                ("hobbies", models.JSONField(blank=True, default=list, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "casual_image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="casual_images/"
                    ),
                ),
                (
                    "casual_image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="casual_images/"
                    ),
                ),
                (
                    "casual_image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="casual_images/"
                    ),
                ),
                (
                    "nationalities",
                    models.ManyToManyField(
                        blank=True, related_name="reacts", to="core.country"
                    ),
                ),
                (
                    "positions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="brothers_in_position",
                        to="core.position",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="position",
            name="brothers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select brothers who held this position.",
                related_name="positions_held_by_brothers",
                to="core.react",
            ),
        ),
    ]
