# Generated by Django 4.1.13 on 2024-10-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="end",
        ),
        migrations.RemoveField(
            model_name="position",
            name="start",
        ),
        migrations.AddField(
            model_name="position",
            name="end_month",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="position",
            name="end_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="position",
            name="start_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="start_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
