# Generated by Django 4.1.13 on 2024-10-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_position_end_remove_position_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="end_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=9,
                null=True,
            ),
        ),
    ]
