# Generated by Django 4.1.13 on 2024-10-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_position_end_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="react",
            name="crossing_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="react",
            name="crossing_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
