# Generated by Django 4.1.13 on 2025-08-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_react_graduating_month_react_graduating_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brother",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("line_name", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("class_field", models.CharField(blank=True, max_length=50)),
                ("big_id", models.IntegerField(blank=True, null=True)),
                ("little_ids", models.JSONField(blank=True, default=list, null=True)),
                ("major", models.CharField(blank=True, max_length=100)),
                ("hobbies", models.JSONField(blank=True, default=list, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "casual_image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="casual_images/"
                    ),
                ),
                (
                    "casual_image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="casual_images/"
                    ),
                ),
                (
                    "casual_image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="casual_images/"
                    ),
                ),
                (
                    "crossing_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "crossing_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "graduating_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "graduating_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Brothers",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["title"]},
        ),
        migrations.DeleteModel(
            name="React",
        ),
        migrations.AddField(
            model_name="brother",
            name="nationalities",
            field=models.ManyToManyField(
                blank=True, related_name="brothers", to="core.country"
            ),
        ),
        migrations.AddField(
            model_name="brother",
            name="positions",
            field=models.ManyToManyField(
                blank=True, related_name="brothers_in_position", to="core.position"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="brothers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select brothers who held this position.",
                related_name="positions_held",
                to="core.brother",
            ),
        ),
    ]
